### ISSUE TITLE
hi, msantos, can you help me? For Termux

### ISSUE THREAD

**Issue by mvwtest** [msantos/xmppipe#5]
I want make this project to the termux.
i get this:
make: *** [Makefile:57: xmppipe] Error 1

and in the windows cygwin64 :
make: *** [Makefile:57: xmppipe] Error 1

but,i make the libstrophe is 100%complete and worked Ok.

can you tell me ,any help,tank you

**Comment by msantos** [comment]
@mvwtest just tested and the compile works with the termux libstrophe package

```
apt install libstrophe
RESTRICT_PROCESS=rlimit make clean all
```

If libstrophe is installed outside the library search path, set up the link flags:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path/to/libstrophe"
export XMPPIPE_CFLAGS="-I /path/to/libstrophe"
export XMPPIPE_LDFLAGS="-L /path/to/libstrophe"
RESTRICT_PROCESS=rlimit make clean all
```

**Comment by mvwtest** [comment]
thank you .
 apt install libstrophe. failed
i use this way install it:
dpkg -i libstrophe_0.11.0_aarch64.deb
file:
https://mirrors.nju.edu.cn/termux/apt/termux-main/pool/main/libs/libstrophe/libstrophe_0.11.0_aarch64.deb
-----------------------------------------------------------------------------------------------------------
$:RESTRICT_PROCESS=rlimit make clean all
i get this:

/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/lib/libstrophe.so: undefined reference to `X509_get_issuer_name@OPENSSL_1_1_0'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/lib/libstrophe.so: undefined reference to `ASN1_INTEGER_to_BN@OPENSSL_1_1_0'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/lib/libstrophe.so: undefined reference to `SSL_free@OPENSSL_1_1_0'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/lib/libstrophe.so: undefined reference to `PEM_read_bio_X509@OPENSSL_1_1_0'
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /data/data/com.termux/files/usr/lib/libstrophe.so: undefined reference to `d2i_GENERAL_NAMES@OPENSSL_1_1_0'
clang-9: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:57: xmppipe] Error 1
$
-----------------------------------------------------------------------
thank you again

**Comment by mvwtest** [comment]
thank you,
i got,sucssfull make it,and run it
-----------------------------------------------------------------
 just ,i got a newest:
-------------------------------------------------------
 $ ./xmppipe -u xmpptest002@xmpp.jp -p 12345678
WARNING: linker: /data/data/com.termux/files/home/xmppipe/xmppipe: unsupported flags DT_FLAGS_1=0x8000001

thank you again

**Comment by msantos** [comment]
@mvwtest see the termux faq

https://wiki.termux.com/wiki/FAQ#Why_does_a_compiled_program_show_warnings

For the install issue, install termux using the fdroid repository: https://github.com/termux/termux-app#f-droid

**Comment by mvwtest** [comment]
thank you ,you are Master.  i got it 

 work  is very good.
./xmppipe -u 'JID1' -p **** --chat JID2  <--> Other client(Gajim/psi+..... ) use 'JID2'.    === Builtifull


When i use this way on 2 Termux:

./xmppipe -u 'JID1' -p ****' --chat JID2  <----->(Other device) ./xmppipe -u 'JID2' -p ***** --chat JID1  
 
here they can `t send and recive  message.

how can i do it
thank you

**Comment by msantos** [comment]
`--chat` requires a fully qualified JID. Make sure the JID is in format: `--chat JID1@example.com`

Otherwise, run in verbose mode and post the output: `xmppipe -vvv ...`
